### PR TITLE
Update to USWDS 2.0

### PR DESCRIPTION
**Pull request by blacktm**
See convo in #171

### CODE REVIEW

**Comment by blacktm** [comment]
This is coming along, just updating all the HTML templates and layouts takes a while, especially since many have embedded Liquid logic to generate them (e.g. can't just copy and paste from the USWDS code examples).

**Comment by thisisdano** [comment]
Test this in your projects. Use the following in your project gemfile:
```
gem 'uswds-jekyll', :git => 'https://github.com/18F/uswds-jekyll.git', :branch => 'update-uswds-2.0'
```

Next steps:
- [ ] More testing
- [ ] Update documentation
- [ ] Migration guide

**Comment by afeld** [comment]
Hey hey! A little worried that this pull request has gotten so large that it's basically unreviewable...anything that can be done to break down the changes?

**Comment by pkarman** [comment]
FYSA: I am using the branch in this PR successfully in a project. Would love to see an upgrade to 2.8.0 and getting it merged. Happy to help in whatever way I can.

**Comment by afeld** [comment]
https://github.com/18F/uswds-jekyll/issues/171#issuecomment-665328833

**Comment by afeld** [comment]
Restored the branch so that sites that still depend on it don't break.

**Pull request merged**
