### PR TITLE
Add identifier component and config

### PR DESCRIPTION
**Pull request by thisisdano**
**Requires USWDS 2.9.0**

This adds a [USWDS identifier](https://designsystem.digital.gov/components/identifier/) to the bottom of the page template, under the site footer. The identifier is a complement to the USWDS banner. It connects a site to its parent agency and includes [general required links](https://digital.gov/resources/required-web-content-and-links/). 

This is a component we're trying to implement across USWDS sites. Where there is overlap with footer content, we recommend removing duplicate content from the footer in favor of the identifier — that is, use the footer is for site-related content, and use the identifier for more agency-level links. 

Since this is a component like the banner that's appropriate for any site that uses this theme, it seems appropriate to include it in the theme. If there's a way to make its configuration simpler (like adding GSA/TTS defaults, perhaps), i could be for it.

### CODE REVIEW

**Comment by ryanhofdotgov** [comment]
Just a comment as a user of the pre-release anchor/identifier component for a TTS guide...

In the guides that I surveyed (e.g., 18F UX guide), the footer was no longer used, just the identifier – everything they needed fit there.

But as the "last modified" feature and the "edit this page" feature are tied to the footer,[ I ended up adding those features to my fork of the pre-release identifier component](https://github.com/18F/isildurs-bane/blob/7189475f28eb75919b6ac266eed218cd738a05a1/_includes/footer.html#L14). And if the footer and the identifier were both turned on, then the identifier's last modified/edit this page were automatically hidden; you'd have to enable the footer's feature in that case.

Not sure how this fits with your vision of the component, but just wanted to share this use case. Thanks!

**Comment by thisisdano** [comment]
@ryanhofdotgov I appreciate that perspective. While I currently don't recommend modifying the identifier (for consistency reasons I'd prefer content like that in the site footer for now) I think I _do_ agree that there's more data or content that might be appropriate for the component. In the name of continuity, I think there's a great argument to be made that a page's last-changed data (with a link to GH if possible) is something we should make implement across more sites. There's perhaps _more_ page metadata that might also deserve to be shown on every page, and together these data might make a really compelling new section for the identifier.

I think USWDS should also revisit the Footer now that the Identifier exists, and work to make that component more useful and better serve site needs.

**Comment by ryanhofdotgov** [comment]
@thisisdano Thanks – makes complete sense.

**Comment by afeld** [comment]
As a "for now" solution, could we split the difference?

- Use the existing `footer` config to populate the Identifier
- Have things that don't fit the Identifier (e.g. "edit on GitHub") show up in a narrow bar above the Identifier, but otherwise mostly scrap the existing footer

image

Since uswds-jekyll is meant to be opinionated, not concerned about a visual breaking change so much as a configuration one. In other words, as long as sites that use this theme can `bundle update` and their site doesn't completely break, I'm good with any changes as a minor version bump.

**Comment by Sgtpluck** [comment]
@thisisdano @afeld do you all know if there is going to be any progress here? i was looking to implement this on the engineering handbook and since all this work has been done already, would rather just piggyback rather than do new work there! 

please let me know if there is anything i can do to help move this forward.

**Comment by adborden** [comment]
Hey folks, the @18F/tts-tech-portfolio is putting this repository into "maintenance mode" and will only accept fixes for the time being. Tech Portfolio and TTS Digital Council are working on a strategy for TTS microsites which will inform the future of this theme.

Rather than leave open pull requests to go stale, we are respectfully going to close this PR. You can [provide any feedback by opening a new issue](https://github.com/18F/uswds-jekyll/issues/new).

**Pull request closed without merging**
