### PR TITLE
Remove scss folder from USWDS assets

### PR DESCRIPTION
**Pull request by hursey013**
The SASS files are already being copied into `/_sass` so we it is duplicative to also have the same set of files in `/assets/uswds/scss`.

I've update the `update-assets` npm task to exclude this folder during future updates of the USWDS as well.

### CODE REVIEW

**Comment by line47** [comment]
I'm wondering if we need the compiled CSS files and the `/assets/uswds/css` folder either ?

**Comment by hursey013** [comment]
Yeah, I had originally taken it out, but opted to leave it in for folks that want to define their own set of stylesheets using `site.styles`. The way it's configured now is that if `site.styles` is used, then nothing at all is included automatically, so in order to include USWDS, you would either need to include the sass file or the compiled CSS. I'm thinking that's going to be a very small percentage of folks though, so getting rid of it is also an option to simplify things.

**Comment by line47** [comment]
I was wondering about that. Does it make sense to set the site up by default to be ready for style configuration? IE set the USWDS styles as well as a main styles file configured in the _config.yml ?

**Comment by hursey013** [comment]
What about including an empty placeholder sass file in the `_sass` directory that is imported into the main css by default? That way if someone wants to either use sass or normal css they can just drop it right into that place holder file?

**Comment by line47** [comment]
Yeah I think something that that would be good 👍

**Comment by line47** [comment]
Maybe a separate PR for that work?

**Pull request merged**
