### PR TITLE
allow for logo only header a la 18f

### PR DESCRIPTION
**Pull request by lauraGgit**

### CODE REVIEW

**Comment by ryanhofdotgov** [comment]
I'll defer to @thisisdano, but here's my two cents:
* It might be better to do this as a local customization, something like [this in the ux-guide](https://github.com/18F/ux-guide/blob/696ab51dd6b956b5fd08ec8662f39fb4a9a47aef/_sass/_uswds-theme-custom-styles.scss#L55)? Adding this to the config file increases the footprint of the template "API" ever so slightly, and that should be weighed against frequency of use, etc.
* If adding this config setting ends up being the right way to go, for backwards compatibility I'd recommend inverting the boolean check in the markup. This way, if the new config setting is not present in a preexisting config file, nothing changes to its rendered site.

**Comment by lauraGgit** [comment]
@ryanhofdotgov thanks for the feedback.

For context, I'd looked at isildur-bane and saw that you have to have the full header includes to have this as a local customization which would make it harder to keep it in sync with new uswds versions vs, a few additional lines in the theme here. I could be persuaded otherwise.

**Comment by peterrowland** [comment]
I just worked on this in our efforts update the 18f website use USWDS2 by pulling in the template and customizing it to remove the text and increase the size of the logo. I'm a newbie to this, but being able to set in the configuration along with the logo size would be useful.

**Comment by adborden** [comment]
Hey folks, the @18F/tts-tech-portfolio is putting this repository into "maintenance mode" and will only accept fixes for the time being. Tech Portfolio and TTS Digital Council are working on a strategy for TTS microsites which will inform the future of this theme.

Rather than leave open pull requests to go stale, we are respectfully going to close this PR. You can [provide any feedback by opening a new issue](https://github.com/18F/uswds-jekyll/issues/new).

**Pull request closed without merging**
