### PR TITLE
Adds an optional header logo to header.yml

### PR DESCRIPTION
**Pull request by rahearn**
Potential implementation for #124.

I used the `display-icon` helper from the USWDS files, but I'm not super happy about passing a blank icon filename and then overriding it.

### CODE REVIEW

**Comment by line47** [comment]
Thanks for this @rahearn 🎉 
What about adding the header logo as an `img` tag like seen here instead of a background image? 
https://18f.gsa.gov/

**Comment by rahearn** [comment]
I started down that path, but went with this approach because it's how the [USWDS v2 homepage](https://v2.designsystem.digital.gov/) handles the header logo so I figured this would be more future proof. Happy to switch it up if you disagree.

**Comment by line47** [comment]
Thanks for clarifying :)
I'm wondering if we want to go down the path of combining USWDS 2.0 features into USWDS 1.X.

It might be better to incorporate this solution into a USWDS 2.0 Jekyll theme (which doesn't exist yet) 
🤔https://github.com/18F/uswds-jekyll/issues/171

**Comment by rahearn** [comment]
OK. I'll switch this up to an `` based solution

**Pull request merged**
