### PR TITLE
add syntax highlighting

### PR DESCRIPTION
**Pull request by afeld**
This will add code syntax highlighting to any sites that use the theme.

### CODE REVIEW

**Comment by ryanhofdotgov** [comment]
At the risk of bike shedding, I'm on the fence with this one – here's what it looks like when applied to the Engineering guide:
[Before](https://engineering.18f.gov/css/formatting/)
[After](https://federalist-0fc100fe-c4d0-4b8f-bd4f-7392edd7c16d.app.cloud.gov/preview/18f/development-guide/rmh-highlight-examples/css/formatting/)

I think better syntax highlighting in general would be an improvement to websites showing code, but my first reaction to this particular theme (at least for CSS examples) was sorta "blech". Doing a quick contrast check on the orange color used for CSS properties in above example, it has a contrast ratio of `2.8:1` – WCAG AA wants at least `4.5:1`, AAA wants `7:1`. Maybe a theme with more muted, darker foreground colors for all syntax elements?

Are their other websites in TTS that would regularly show code aside from [engineering.18f.gov](https://engineering.18f.gov/)?

**Comment by ryanhofdotgov** [comment]
For others following along, here is the [theme preview page](http://jwarby.github.io/jekyll-pygments-themes/languages/javascript.html) for `jekyll-pygments-themes`.

**Comment by afeld** [comment]
> this particular theme (at least for CSS examples) was sorta "blech"

Zero strong feelings about which theme to use. That was the highest-contrast + nicest looking theme I saw in a quick search.

> Are there other websites in TTS that would regularly show code aside from engineering.18f.gov?

First example I could find:

https://handbook.tts.gsa.gov/contributing/#front-matter

While not _all_ sites will have code snippets, I think of uswds-jekyll as being a "batteries included" theme, so that the majority of sites using it should require minimal configuration. I think including that small stylesheet and being able to improve things like the contrast in a central place is preferable to having slightly slimmer payload for sites that don't need it, and more work for those that do.

**Comment by ryanhofdotgov** [comment]
To clarify – no objections about putting the styles in here – I love batteries included. Just wanted to see if there were other existing sites where we could view these styling changes in context.

I think the main thing before merging into the template is just find a style where the colors maintain at least the WCAG AA contrast ratio of 4.5:1. That's the compliance threshold we use in our sample QASP, and what `pa11y` complains about (default settings) when I run it against the `After` version of that CSS formatting page in the Engineering guide.

**Comment by adborden** [comment]
Hey folks, the @18F/tts-tech-portfolio is putting this repository into "maintenance mode" and will only accept fixes for the time being. Tech Portfolio and TTS Digital Council are working on a strategy for TTS microsites which will inform the future of this theme.

Rather than leave open pull requests to go stale, we are respectfully going to close this PR. You can [provide any feedback by opening a new issue](https://github.com/18F/uswds-jekyll/issues/new).

**Pull request closed without merging**
