### PR TITLE
Adding edit page link and adding page meta section

### LINKED ISSUE #75: Add edit this page link
Add an "edit this page" link as a configuration option to the `footer.yml` file that links to the current page file in edit mode on GitHub

- [x] option for toggling on and off
- [x] option for changing the text

### PR DESCRIPTION
**Pull request by line47**
**Preview**
https://federalist-proxy.app.cloud.gov/preview/18f/uswds-jekyll/sw-edit-page/

- Combined last updated and edit page into the same section
- Added edit this page GitHub link 

**Still need to figure out**
- Placement for last updated and edit page section. Some sort of margin/padding is needed because there is none. 

closes #75

### CODE REVIEW

**Comment by line47** [comment]
Looking for thoughts on best way to implement this and any future page meta info 🤔

**Comment by hursey013** [comment]
What do you think about separating the last updated text from the github link? I like where the `Last updated` text is, but could the `Edit this page` link go in the the actual footer,  either below the agency name or contact section?

**Comment by line47** [comment]
I'm totally open to that. I wanted to see where might make the best sense, I feel the footer is the best place for sure 👍 .

I'll update this PR with those changes

**Comment by line47** [comment]
Good to note 👍

**Pull request merged**
